export const defaultPoint = {
  reps1: null,
  weight1: null,
  time_in_seconds1: null,
  rest_in_seconds1: 0,
  failure1: null,
  intensity1: 0,
  is_pr1: null,

  reps2: null,
  weight2: null,
  time_in_seconds2: null,
  rest_in_seconds2: 0,
  failure2: null,
  intensity2: 0,
  is_pr2: null,

  reps3: null,
  weight3: null,
  time_in_seconds3: null,
  rest_in_seconds3: 0,
  failure3: null,
  intensity3: 0,
  is_pr3: null,

  reps4: null,
  weight4: null,
  time_in_seconds4: null,
  rest_in_seconds4: 0,
  failure4: null,
  intensity4: 0,
  is_pr4: null,

  reps5: null,
  weight5: null,
  time_in_seconds5: null,
  rest_in_seconds5: 0,
  failure5: null,
  intensity5: 0,
  is_pr5: null,

  reps6: null,
  weight6: null,
  time_in_seconds6: null,
  rest_in_seconds6: 0,
  failure6: null,
  intensity6: 0,
  is_pr6: null,

  reps7: null,
  weight7: null,
  time_in_seconds7: null,
  rest_in_seconds7: 0,
  failure7: null,
  intensity7: 0,
  is_pr7: null,
};

export const chartPressInitialState = {
  failure1: 0,
  reps1: 0,
  time_in_seconds1: 0,
  intensity1: 0,
  rest_in_seconds1: 0,
  weight1: 0,
  is_pr1: 0,

  failure2: 0,
  reps2: 0,
  intensity2: 0,
  rest_in_seconds2: 0,
  time_in_seconds2: 0,
  weight2: 0,
  is_pr2: 0,

  failure3: 0,
  reps3: 0,
  intensity3: 0,
  rest_in_seconds3: 0,
  time_in_seconds3: 0,
  weight3: 0,
  is_pr3: 0,

  failure4: 0,
  reps4: 0,
  intensity4: 0,
  rest_in_seconds4: 0,
  time_in_seconds4: 0,
  weight4: 0,
  is_pr4: 0,

  failure5: 0,
  reps5: 0,
  intensity5: 0,
  rest_in_seconds5: 0,
  time_in_seconds5: 0,
  weight5: 0,
  is_pr5: 0,

  failure6: 0,
  reps6: 0,
  intensity6: 0,
  rest_in_seconds6: 0,
  time_in_seconds6: 0,
  weight6: 0,
  is_pr6: 0,

  failure7: 0,
  reps7: 0,
  intensity7: 0,
  rest_in_seconds7: 0,
  time_in_seconds7: 0,
  weight7: 0,
  is_pr7: 0,
};
